### ISSUE TITLE
TSC takes a very long time to compile

### ISSUE THREAD

**Issue by KSXGitHub** [kgtkr/typepark#1]
When I do this:

```typescript
import * as typepark from 'typepark'
export {typepark}
```

And then run `tsc`, TSC take a long time (possibly forever) to compile. I have cancelled the compilation due to my lack of patient. Did you check if there's infinite recursion in your type definitions, namely `Concat`?

**Comment by kgtkr** [comment]
Are you using typescript@next?

**Comment by KSXGitHub** [comment]
My bad.
